PAGE_TABLE_SIZE = 256
PHYSICAL_MEMORY_SIZE = 256
PHYSICAL_MEMORY_SIZE_Q = 256
TLB_SIZE = 16
DEFAULT_VALUE = PAGE_TABLE_SIZE - 1
BS_FILE = 'BACKING_STORE.bin'


def change_attributes(pms):
    global PHYSICAL_MEMORY_SIZE_Q
    PHYSICAL_MEMORY_SIZE_Q = pms
